#pragma config(Sensor, in8,    armpit,         sensorPotentiometer)
#pragma config(Sensor, dgtl9,  lshaft,         sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rshaft,         sensorQuadEncoder)
#pragma config(Motor,  port1,           claw1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	wait1Msec(100);  // 0.1 Second Delay


/*



*/
	motor[lift1] = -127;//lift up
	motor[lift2] = -127;
	wait1Msec(500);
	motor[lift1] = 0;
	motor[lift2] = 0;

	wait1Msec(100);
	motor[claw1] = 127;// claw forwards
	motor[claw2] = 127;
	wait1Msec(650);
	motor[claw1] = 10;
	motor[claw2] = -10;

/*	motor[lift1] = -100;//lift up
	motor[lift2] = -100;
	wait1Msec(585);
	motor[lift1] = 0;
	motor[lift2] = 0;
	wait1Msec(400);
*/
	SensorValue(armpit) = 0; //ranges from 0 - 4096

while(SensorValue(armpit)< position){
	motor[lift1] = -100;
	motor[lift2] = -100;
}
		//Clear Encoders
	SensorValue[rshaft] = 0;

	while(SensorValue[rshaft] < 1450)  // While less than x rotations on the leftEncoder...
	{
		//...Move Forward
		motor[rightMotor] = 100;//forards 40 inches
		motor[leftMotor] = 100;

	}

		SensorValue[rshaft] = 0;
	while(SensorValue[rshaft] > -360){
	motor[rightMotor] = -100;
	motor[leftMotor] = -100;
}
  wait1Msec(200);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		int leftstick = vexRT[Ch3];
		int rightstick = vexRT[Ch2];
		int liftbuttonU = vexRT[Btn6U];
		int liftbuttonD = vexRT[Btn6D];
		int clawopen = vexRT[Btn5U];
		int clawclose = vexRT[Btn5D];


		//left motor control
		if (leftstick > 10 || leftstick < -10){
			motor [leftMotor] = leftstick;
			//			motor [leftMotorB] = leftstick;
		}
		else
			motor [leftMotor] = 0;
		//			motor [leftMotorB] = 0;

		//right motor control
		if (rightstick > 10 || rightstick <-10){
			motor [rightMotor] = rightstick;
			//			motor [rightMotorB] = rightstick;
		}
		else
			motor [rightMotor] = 0;
		//			motor [rightMotorB] = 0;

		//Lift control
		if (liftbuttonU == 1){
			motor [lift1] = -127;
			motor[lift2] = -127;
		}
		else if (liftbuttonD == 1){
			motor [lift1] = 127;
			motor[lift2] = 127;
		}
		else {
			motor [lift1] = 0;
			motor[lift2] = 0;
		}
		//Claw control
		if (clawopen == 1){
			motor [claw1] = 127;
			motor [claw2] = 127;
		}
		else if (clawclose == 1){
			motor [claw1] = -127;
			motor [claw2] = -127;
		}
		else{
			motor[claw1] = 10;
			motor[claw2] = -10;}
	}

}
